### ISSUE TITLE
ir.farshid_roohi.customadapterrecyclerview.databinding.MyItemBinding not there

### ISSUE THREAD

**Issue by asystat** [FarshidRoohi/CustomAdapterRecyclerview#4]
Hello Farshid,
in the sample you reference this file but it doesn't exist in the project. Can you provide it or guide how to execute the provided sample?
Thanks!

**Comment by FarshidRoohi** [comment]
hi
please read readme document  and read about dataBinding
[document](https://github.com/FarshidRoohi/CustomAdapterRecyclerview) and [dataBinding](https://developer.android.com/topic/libraries/data-binding)

good luck :)
